Add reactor
Metroscope-dev/metroscope-modeling-library pull request #481
Opened 2024-04-09 09:45 UTC by moritzn-met

## Goal

Add reactor component. (Fix #476) Its an additional component, I didnt manage to extend this to use for Steam Generator. (BC of different design, and purge)

## Type of change 

- [ ] Bugfix
- [ ] New feature
- [ ] Refactoring change
- [ ] Release & Version Update (don't forget to change the version number in `package.mo`)

Will it break anything in previous models ?

- [ ] Breaking change (If yes, make sure to point it out in the changelog)
- [ ] Non-Breaking change

## Checklist

- [ ] I have added the appropriate tags, reviewers, projects (and detailed the size and priority of my PR) and linked issues to this PR
- [ ] I have performed a self-review of my own code
- [ ] I have checked that all existing tests pass.
- [ ] I have added/updated tests that prove my development works and does not break anything.
- [ ] I have made corresponding changes or additions to the documentation (in [Notion documentation](https://www.notion.so/metroscope/Metroscope-Modeling-Library-Documentation-MML3-WIP-50c8703c294446059d3b4a70d6ae4a71))
- [ ] I have added corresponding entries to the [Changelog](../CHANGELOG.md)
- [ ] I have checked for conflicts with target branch, and merged/rebased in consequence

You can also fill these out after creating the PR, but make sure to **check them all before submitting your PR for review**.

2024-04-09 12:01 UTC, hadrienp-met commented
I think you forgot to add the test models to your commit, the "Add tests" has no changes to show

2024-04-09 14:14 UTC, moritzn-met commented
> I think you forgot to add the test models to your commit, the "Add tests" has no changes to show

Ups yeah something went wrong. I added the tests!

2024-04-11 11:44 UTC, hadrienp-met approved these changes
A few comments, but it looks good to me

2024-04-11 11:44 UTC, hadrienp-met commented on MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Reactor.mo
> +    feed_water_flow_rate_measurement_bias = 0; // a bias of +5 kg/s means that 1005 kg/s is measured, while only 1000 kg/s actually go into the SG
```suggestion
    feed_water_flow_rate_measurement_bias = 0; // a bias of +5 kg/s means that 1005 kg/s is measured, while only 1000 kg/s actually go into the reactor

```

2024-04-11 11:44 UTC, hadrienp-met commented on MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Reactor.mo
> +  Q_feedwater_measured = feedwater_sink.Q_in + feed_water_flow_rate_measurement_bias; // Note : feedwater_sink.Q_in is the actual flow going into the steam generator
```suggestion
  Q_feedwater_measured = feedwater_sink.Q_in + feed_water_flow_rate_measurement_bias; // Note : feedwater_sink.Q_in is the actual flow going into the reactor

```

2024-04-11 11:44 UTC, hadrienp-met commented on MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Reactor.mo
> +  thermal_power = Q_steam*steam_source.h_out - Q_feedwater_measured*feedwater_sink.h_in; // thermal power here refers to the estimation of thermal power so it corresponds to the measured feedwater fl
We can simplify
```suggestion
  thermal_power = Q_feedwater_measured * (steam_source.h_out - feedwater_sink.h_in); // thermal power here refers to the estimation of thermal power so it corresponds to the measured feedwater flow rate

```

2024-04-11 11:44 UTC, hadrienp-met commented on MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Reactor.mo
> +  Q_steam = Q_feedwater_measured;
Do we still need `Q_steam `? as it is equal to `Q_feedwater_measured`

2024-04-11 11:52 UTC, hadrienp-met requested changes
Don't forget to update the changelog and add the component to the documentation

2024-04-11 15:05 UTC, hadrienp-met requested changes
You need to update the changelog

2024-04-11 15:09 UTC, hadrienp-met approved these changes

2024-04-15 09:41 UTC, merged